# Generated by Django 5.1 on 2024-11-24 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='FechaEntrada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='habitaciones',
        ),
        migrations.AddField(
            model_name='reserva',
            name='habitaciones',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Hotel.habitacion', verbose_name='Habitaciones'),
            preserve_default=False,
        ),
    ]
