# Generated by Django 5.1 on 2024-12-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='codigo_factura',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_emision',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de Emisión'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='monto_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Total'),
        ),
    ]
