# Generated by Django 5.1 on 2024-11-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='original_FechaEntrada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='original_FechaSalida',
            field=models.DateField(blank=True, null=True),
        ),
    ]
