# Generated by Django 5.1 on 2024-11-26 03:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_alter_reserva_fechaentrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='numero_habitacion',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Habitación'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='precio_habitacion',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='habitaciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hotel.habitacion', verbose_name='Habitaciones'),
        ),
    ]
