# Generated by Django 5.1 on 2024-11-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_reserva_original_fechaentrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado_reserva',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('CHECK-OUT', 'Check-Out')], default='PENDIENTE', max_length=20, verbose_name='Estado de Reserva'),
        ),
    ]
