# Generated by Django 5.1 on 2024-12-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_alter_reserva_codigo_factura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='habitaciones_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='habitaciones',
        ),
        migrations.AddField(
            model_name='reserva',
            name='habitaciones',
            field=models.ManyToManyField(to='Hotel.habitacion', verbose_name='Habitaciones'),
        ),
    ]
