# Generated by Django 5.1 on 2024-11-26 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0003_alter_habitacion_numero_habitacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='habitaciones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Hotel.habitacion', verbose_name='Habitaciones'),
        ),
    ]
