# Generated by Django 5.1 on 2024-12-12 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0003_reserva_habitaciones_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='habitaciones_count',
        ),
    ]
