# Generated by Django 5.1 on 2024-11-26 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0004_alter_reserva_habitaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='habitaciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hotel.habitacion', verbose_name='Habitaciones'),
        ),
    ]
