# Generated by Django 5.1 on 2024-12-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0004_remove_reserva_habitaciones_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='monto_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Monto Total'),
        ),
    ]
