# Generated by Django 5.1 on 2024-12-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0005_alter_reserva_monto_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='habitaciones_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='monto_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Total'),
        ),
    ]
