# Generated by Django 5.1 on 2024-12-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0006_reserva_habitaciones_count_alter_reserva_monto_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='habitaciones_count',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='monto_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Monto Total'),
        ),
    ]
