# Generated by Django 5.1 on 2024-12-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0007_remove_reserva_habitaciones_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='habitaciones_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
