# Generated by Django 5.1 on 2024-12-18 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0009_alter_reserva_monto_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='monto_total',
        ),
    ]
